/** @format */

export const menus = [
  {
    id: 1,
    parentId: 0,
    name: 'Sum',
    path: '/sum',
    component: '',
    title: '统计',
    sort: '1',
  },
  {
    id: 111,
    parentId: 1,
    name: 'Sum111',
    path: '/need/home',
    component: 'views/test',
    title: '页面一',
    sort: '1',
  },
  {
    id: 112,
    parentId: 1,
    name: 'Sum112',
    path: '/need/home',
    component: 'views/home',
    title: '页面二',
    sort: '1',
  },
  {
    id: 2,
    parentId: 0,
    name: 'Sum2',
    path: '/need/test1',
    component: '',
    title: '页面二',
    sort: '1',
  },
  {
    id: 221,
    parentId: 2,
    name: 'Sum331',
    path: '/need/test3',
    component: 'views/test',
    title: '页面二1',
    sort: '1',
  },
  {
    id: 222,
    parentId: 2,
    name: 'Sum222',
    path: '/need/test2',
    component: 'views/test',
    title: '页面二2',
    sort: '1',
  },
  {
    id: 3,
    parentId: 0,
    name: 'Sum3',
    path: '/need/test1',
    component: '',
    title: '页面3',
    sort: '1',
  },
  {
    id: 331,
    parentId: 3,
    name: 'Sum331',
    path: '/need/test31',
    component: 'views/index1',
    title: '测试标题',
    sort: '1',
  },
  {
    id: 333,
    parentId: 3,
    name: 'Sum332',
    path: '/need/test32',
    component: 'views/index2',
    title: '测试标题标题',
    sort: '1',
  },
  {
    id: 333,
    parentId: 3,
    name: 'Sum333',
    path: '/need/test33',
    component: 'views/index3',
    title: '页面二3',
    sort: '1',
  },
  {
    id: 333,
    parentId: 3,
    name: 'Sum334',
    path: '/need/test34',
    component: 'views/index4',
    title: '页面二4',
    sort: '1',
  },
  {
    id: 333,
    parentId: 3,
    name: 'Sum335',
    path: '/need/test35',
    component: 'views/index5',
    title: '页面二5',
    sort: '1',
  },
  {
    id: 333,
    parentId: 3,
    name: 'Sum336',
    path: '/need/test36',
    component: 'views/index6',
    title: '页面二6',
    sort: '1',
  },
]
