/** @format */

export const menus = [
  {
    id: 991,
    parentId: 0,
    name: 'need/sys/my',
    path: '/need/sys/my',
    component: 'views/sys/my',
    title: '个人中心',
    sort: '1',
    hidden: true,
  },
  {
    id: 992,
    parentId: 0,
    name: 'need/sys/notice',
    path: '/need/sys/notice',
    component: 'views/sys/notice',
    title: '通知中心',
    sort: '1',
    hidden: true,
  },
  {
    id: 3,
    parentId: 0,
    name: 'Sum3',
    path: '',
    component: '',
    title: '页面',
    sort: '1',
  },
  {
    id: 331,
    parentId: 3,
    name: 'need/test31',
    path: '/need/test31',
    component: 'views/index1',
    title: '测试标题',
    sort: '1',
  },
  {
    id: 333,
    parentId: 3,
    name: 'need/test32',
    path: '/need/test32',
    component: 'views/index2',
    title: '测试标题标题',
    sort: '1',
  },
  {
    id: 333,
    parentId: 3,
    name: 'need/test33',
    path: '/need/test33',
    component: 'views/index3',
    title: '页面二3',
    sort: '1',
  },
  {
    id: 333,
    parentId: 3,
    name: 'need/test34',
    path: '/need/test34',
    component: 'views/index4',
    title: '页面二4',
    sort: '1',
  },
  {
    id: 333,
    parentId: 3,
    name: 'need/test35',
    path: '/need/test35',
    component: 'views/index5',
    title: '页面二5',
    sort: '1',
    hidden: true,
  },
  {
    id: 441,
    parentId: 0,
    name: 'need/test36',
    path: '/need/test36',
    component: 'views/index6',
    title: '页面二6',
    sort: '1',
  },
  {
    id: 551,
    parentId: 0,
    name: 'sys',
    path: '/sys',
    component: 'views/sys/dict',
    title: '系统管理',
    sort: '1',
  },
  {
    id: 552,
    parentId: 551,
    name: 'dict',
    path: '/need/sys/dict',
    component: 'views/sys/dict',
    title: '数据字典',
    sort: '1',
  },
  {
    id: 553,
    parentId: 551,
    name: 'user',
    path: '/need/sys/user',
    component: 'views/sys/user',
    title: '用户管理',
    sort: '1',
  },
  {
    id: 554,
    parentId: 551,
    name: 'role',
    path: '/need/sys/role',
    component: 'views/sys/role',
    title: '角色管理',
    sort: '2',
  },
  {
    id: 555,
    parentId: 551,
    name: 'menu',
    path: '/need/sys/menu',
    component: 'views/sys/menu',
    title: '菜单管理',
    sort: '3',
  },
]
