/** @format */

export const menus = [
  {
    id: 3,
    parentId: 0,
    name: 'Sum3',
    path: '',
    component: '',
    title: '页面3',
    sort: '1',
  },
  {
    id: 331,
    parentId: 3,
    name: 'need/test31',
    path: '/need/test31',
    component: 'views/index1',
    title: '测试标题',
    sort: '1',
  },
  {
    id: 333,
    parentId: 3,
    name: 'need/test32',
    path: '/need/test32',
    component: 'views/index2',
    title: '测试标题标题',
    sort: '1',
  },
  {
    id: 333,
    parentId: 3,
    name: 'need/test33',
    path: '/need/test33',
    component: 'views/index3',
    title: '页面二3',
    sort: '1',
  },
  {
    id: 333,
    parentId: 3,
    name: 'need/test34',
    path: '/need/test34',
    component: 'views/index4',
    title: '页面二4',
    sort: '1',
  },
  {
    id: 333,
    parentId: 3,
    name: 'need/test35',
    path: '/need/test35',
    component: 'views/index5',
    title: '页面二5',
    sort: '1',
  },
  {
    id: 333,
    parentId: 3,
    name: 'need/test36',
    path: '/need/test36',
    component: 'views/index6',
    title: '页面二6',
    sort: '1',
  },
]
